/**
 * Registro de todos os blocos disponíveis pra paleta do construtor visual —
 * um item por `FlowNodeType`. `dataPadrao()` é o `data` inicial de um nó recém
 * arrastado pro canvas (sempre chamada de novo, nunca compartilha objeto entre
 * dois nós soltos na mesma sessão).
 */

import type { FlowNodeCategory, FlowNodeType } from "./types";

export type BlocoDefinicao = {
  tipo: FlowNodeType;
  categoria: FlowNodeCategory;
  label: string;
  descricao: string;
  icone: string;
  corClasse: string;
  dataPadrao: () => object;
};

/** Cor por categoria — usada tanto na paleta quanto no nó desenhado no canvas. */
export const CATEGORIAS_BLOCOS: {
  id: FlowNodeCategory;
  label: string;
  cor: string;
  corClasse: string;
}[] = [
  { id: "gatilho", label: "Gatilhos", cor: "azul", corClasse: "bg-blue-100 text-blue-700" },
  { id: "condicao", label: "Condições", cor: "roxo", corClasse: "bg-purple-100 text-purple-700" },
  { id: "mensagem", label: "Mensagens", cor: "verde", corClasse: "bg-green-100 text-green-700" },
  { id: "espera", label: "Esperas", cor: "laranja", corClasse: "bg-orange-100 text-orange-700" },
  { id: "acao", label: "Ações", cor: "amarelo", corClasse: "bg-yellow-100 text-yellow-800" },
  { id: "humano", label: "Humano", cor: "rosa", corClasse: "bg-pink-100 text-pink-700" },
  { id: "integracao", label: "Integrações", cor: "cinza-azulado", corClasse: "bg-slate-200 text-slate-700" },
  { id: "fim", label: "Encerramento", cor: "vermelho", corClasse: "bg-red-100 text-red-700" },
];

function corDaCategoria(categoria: FlowNodeCategory): string {
  return CATEGORIAS_BLOCOS.find((c) => c.id === categoria)?.corClasse ?? "bg-gray-100 text-gray-700";
}

export const BLOCOS_DISPONIVEIS: BlocoDefinicao[] = [
  // -------------------------------------------------------------- gatilho --
  {
    tipo: "lead_criado",
    categoria: "gatilho",
    label: "Lead criado",
    descricao: "Dispara quando um novo contato entra no CRM.",
    icone: "UserPlus",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "lead_entrou_etapa",
    categoria: "gatilho",
    label: "Lead entrou na etapa",
    descricao: "Dispara quando o lead entra numa etapa do funil.",
    icone: "LogIn",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({ funilId: "", etapaId: "", disparoImediato: true }),
  },
  {
    tipo: "lead_saiu_etapa",
    categoria: "gatilho",
    label: "Lead saiu da etapa",
    descricao: "Dispara quando o lead sai de uma etapa do funil.",
    icone: "LogOut",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({ funilId: "", etapaId: "", disparoImediato: true }),
  },
  {
    tipo: "lead_parado_etapa",
    categoria: "gatilho",
    label: "Lead parado na etapa",
    descricao: "Dispara quando o lead fica parado numa etapa por um tempo.",
    icone: "Clock",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({ funilId: "", etapaId: "", tempoValor: 2, tempoUnidade: "dias" }),
  },
  {
    tipo: "lead_respondeu",
    categoria: "gatilho",
    label: "Lead respondeu",
    descricao: "Dispara quando o lead responde uma mensagem.",
    icone: "MessageSquareReply",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "lead_nao_respondeu",
    categoria: "gatilho",
    label: "Lead não respondeu",
    descricao: "Dispara quando o lead fica sem responder por um tempo.",
    icone: "MessageSquareOff",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({ tempoValor: 24, tempoUnidade: "horas" }),
  },
  {
    tipo: "palavra_chave",
    categoria: "gatilho",
    label: "Palavra-chave recebida",
    descricao: "Dispara quando a mensagem recebida contém uma palavra-chave.",
    icone: "Hash",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({ palavra: "" }),
  },
  {
    tipo: "mensagem_recebida",
    categoria: "gatilho",
    label: "Mensagem recebida",
    descricao: "Dispara em qualquer mensagem recebida no canal escolhido.",
    icone: "Inbox",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({ canal: "whatsapp" }),
  },
  {
    tipo: "etiqueta_adicionada",
    categoria: "gatilho",
    label: "Etiqueta adicionada",
    descricao: "Dispara quando uma etiqueta é adicionada ao contato.",
    icone: "Tag",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({ etiquetaNome: "" }),
  },
  {
    tipo: "etiqueta_removida",
    categoria: "gatilho",
    label: "Etiqueta removida",
    descricao: "Dispara quando uma etiqueta é removida do contato.",
    icone: "TagOff",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({ etiquetaNome: "" }),
  },
  {
    tipo: "campo_alterado",
    categoria: "gatilho",
    label: "Campo alterado",
    descricao: "Dispara quando um campo do contato muda de valor.",
    icone: "PencilLine",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({ campoNome: "" }),
  },
  {
    tipo: "responsavel_alterado",
    categoria: "gatilho",
    label: "Responsável alterado",
    descricao: "Dispara quando o atendente responsável muda.",
    icone: "UserCog",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "tarefa_criada",
    categoria: "gatilho",
    label: "Tarefa criada",
    descricao: "Dispara quando uma tarefa é criada pro contato.",
    icone: "ListPlus",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({ filtroModo: "qualquer" }),
  },
  {
    tipo: "tarefa_concluida",
    categoria: "gatilho",
    label: "Tarefa concluída",
    descricao: "Dispara quando uma tarefa do contato é concluída.",
    icone: "ListChecks",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({ filtroModo: "qualquer" }),
  },
  {
    tipo: "tarefa_vencida",
    categoria: "gatilho",
    label: "Tarefa vencida",
    descricao: "Dispara quando uma tarefa do contato vence sem ser concluída.",
    icone: "AlarmClockOff",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "consulta_agendada",
    categoria: "gatilho",
    label: "Consulta agendada",
    descricao: "Dispara quando uma consulta é agendada.",
    icone: "CalendarPlus",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "consulta_confirmada",
    categoria: "gatilho",
    label: "Consulta confirmada",
    descricao: "Dispara quando o lead confirma presença na consulta.",
    icone: "CalendarCheck",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "consulta_cancelada",
    categoria: "gatilho",
    label: "Consulta cancelada",
    descricao: "Dispara quando uma consulta é cancelada.",
    icone: "CalendarX",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "cliente_nao_compareceu",
    categoria: "gatilho",
    label: "Cliente não compareceu",
    descricao: "Dispara quando o lead falta a uma consulta agendada.",
    icone: "UserX",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "formulario_preenchido",
    categoria: "gatilho",
    label: "Formulário preenchido",
    descricao: "Dispara quando o lead preenche um formulário do CRM.",
    icone: "FileText",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "pagamento_aprovado",
    categoria: "gatilho",
    label: "Pagamento aprovado",
    descricao: "Dispara quando um pagamento do lead é aprovado.",
    icone: "CircleDollarSign",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "pagamento_pendente",
    categoria: "gatilho",
    label: "Pagamento pendente",
    descricao: "Dispara quando um pagamento fica pendente.",
    icone: "Hourglass",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "pagamento_vencido",
    categoria: "gatilho",
    label: "Pagamento vencido",
    descricao: "Dispara quando um pagamento pendente vence.",
    icone: "CircleAlert",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "aniversario",
    categoria: "gatilho",
    label: "Aniversário do contato",
    descricao: "Dispara na data de nascimento do contato.",
    icone: "Cake",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "data_personalizada",
    categoria: "gatilho",
    label: "Data personalizada",
    descricao: "Dispara numa data específica.",
    icone: "CalendarClock",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "horario_programado",
    categoria: "gatilho",
    label: "Horário programado",
    descricao: "Dispara recorrentemente num horário fixo.",
    icone: "Timer",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({ recorrente: true }),
  },
  {
    tipo: "comentario_instagram",
    categoria: "gatilho",
    label: "Comentário no Instagram",
    descricao: "Dispara quando alguém comenta um post no Instagram.",
    icone: "Instagram",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({ canal: "Instagram", palavraChave: "" }),
  },
  {
    tipo: "comentario_tiktok",
    categoria: "gatilho",
    label: "Comentário no TikTok",
    descricao: "Dispara quando alguém comenta um vídeo no TikTok.",
    icone: "Music2",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({ canal: "TikTok", palavraChave: "" }),
  },
  {
    tipo: "lead_anuncio",
    categoria: "gatilho",
    label: "Lead de anúncio",
    descricao: "Dispara quando um lead chega via Meta/Google/TikTok Ads.",
    icone: "Megaphone",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "webhook_recebido",
    categoria: "gatilho",
    label: "Webhook recebido",
    descricao: "Dispara quando um webhook externo chega.",
    icone: "Webhook",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "integracao_externa",
    categoria: "gatilho",
    label: "Evento de integração externa",
    descricao: "Dispara quando uma integração conectada emite um evento.",
    icone: "Plug",
    corClasse: corDaCategoria("gatilho"),
    dataPadrao: () => ({}),
  },

  // ------------------------------------------------------------- condicao --
  {
    tipo: "condicao_grupo",
    categoria: "condicao",
    label: "Se/então (condição)",
    descricao: "Ramifica o fluxo com base em regras E/OU/NÃO.",
    icone: "GitBranch",
    corClasse: corDaCategoria("condicao"),
    dataPadrao: () => ({ grupo: { id: `grupo-${Date.now()}`, tipo: "E", regras: [], subgrupos: [] } }),
  },

  // ------------------------------------------------------------- mensagem --
  {
    tipo: "mensagem_texto",
    categoria: "mensagem",
    label: "Enviar texto",
    descricao: "Envia uma mensagem de texto simples.",
    icone: "MessageSquare",
    corClasse: corDaCategoria("mensagem"),
    dataPadrao: () => ({ canal: "whatsapp", texto: "" }),
  },
  {
    tipo: "mensagem_imagem",
    categoria: "mensagem",
    label: "Enviar imagem",
    descricao: "Envia uma imagem com legenda opcional.",
    icone: "Image",
    corClasse: corDaCategoria("mensagem"),
    dataPadrao: () => ({ canal: "whatsapp" }),
  },
  {
    tipo: "mensagem_video",
    categoria: "mensagem",
    label: "Enviar vídeo",
    descricao: "Envia um vídeo com legenda opcional.",
    icone: "Video",
    corClasse: corDaCategoria("mensagem"),
    dataPadrao: () => ({ canal: "whatsapp" }),
  },
  {
    tipo: "mensagem_audio",
    categoria: "mensagem",
    label: "Enviar áudio",
    descricao: "Envia um áudio gravado ou escolhido.",
    icone: "Mic",
    corClasse: corDaCategoria("mensagem"),
    dataPadrao: () => ({ canal: "whatsapp" }),
  },
  {
    tipo: "mensagem_documento",
    categoria: "mensagem",
    label: "Enviar documento",
    descricao: "Envia um arquivo (PDF, etc).",
    icone: "FileText",
    corClasse: corDaCategoria("mensagem"),
    dataPadrao: () => ({ canal: "whatsapp" }),
  },
  {
    tipo: "mensagem_contato",
    categoria: "mensagem",
    label: "Enviar contato",
    descricao: "Envia um cartão de contato.",
    icone: "Contact",
    corClasse: corDaCategoria("mensagem"),
    dataPadrao: () => ({ nomeContato: "" }),
  },
  {
    tipo: "mensagem_localizacao",
    categoria: "mensagem",
    label: "Enviar localização",
    descricao: "Envia uma localização (endereço da clínica, etc).",
    icone: "MapPin",
    corClasse: corDaCategoria("mensagem"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "mensagem_botoes",
    categoria: "mensagem",
    label: "Mensagem com botões",
    descricao: "Envia texto com opções de resposta em botões — ramifica o fluxo.",
    icone: "ListTodo",
    corClasse: corDaCategoria("mensagem"),
    dataPadrao: () => ({ canal: "whatsapp", texto: "", opcoes: [] }),
  },
  {
    tipo: "mensagem_lista",
    categoria: "mensagem",
    label: "Mensagem com lista",
    descricao: "Envia texto com opções de resposta em lista — ramifica o fluxo.",
    icone: "List",
    corClasse: corDaCategoria("mensagem"),
    dataPadrao: () => ({ canal: "whatsapp", texto: "", opcoes: [] }),
  },
  {
    tipo: "mensagem_modelo_whatsapp",
    categoria: "mensagem",
    label: "Modelo aprovado do WhatsApp",
    descricao: "Envia um template pré-aprovado da API oficial do WhatsApp.",
    icone: "FileCheck",
    corClasse: corDaCategoria("mensagem"),
    dataPadrao: () => ({ templateId: "" }),
  },
  {
    tipo: "mensagem_email",
    categoria: "mensagem",
    label: "Enviar e-mail",
    descricao: "Envia um e-mail pro contato.",
    icone: "Mail",
    corClasse: corDaCategoria("mensagem"),
    dataPadrao: () => ({ assunto: "", corpo: "" }),
  },
  {
    tipo: "notificacao_interna",
    categoria: "mensagem",
    label: "Notificação interna",
    descricao: "Notifica alguém da equipe dentro do CRM.",
    icone: "BellRing",
    corClasse: corDaCategoria("mensagem"),
    dataPadrao: () => ({ mensagem: "" }),
  },
  {
    tipo: "enviar_formulario",
    categoria: "mensagem",
    label: "Enviar formulário",
    descricao: "Envia um formulário interno do CRM ou um link externo.",
    icone: "ClipboardList",
    corClasse: corDaCategoria("mensagem"),
    dataPadrao: () => ({ formularioOrigem: "interno" }),
  },

  // --------------------------------------------------------------- espera --
  {
    tipo: "aguardar",
    categoria: "espera",
    label: "Aguardar",
    descricao: "Pausa o fluxo por um tempo ou até uma condição acontecer.",
    icone: "Clock3",
    corClasse: corDaCategoria("espera"),
    dataPadrao: () => ({ modo: "horas", valor: 1 }),
  },

  // ----------------------------------------------------------------- acao --
  {
    tipo: "adicionar_etiqueta",
    categoria: "acao",
    label: "Adicionar etiqueta",
    descricao: "Adiciona uma etiqueta ao contato.",
    icone: "TagPlus",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({ etiquetaNome: "" }),
  },
  {
    tipo: "remover_etiqueta",
    categoria: "acao",
    label: "Remover etiqueta",
    descricao: "Remove uma etiqueta do contato.",
    icone: "TagMinus",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({ etiquetaNome: "" }),
  },
  {
    tipo: "alterar_etapa",
    categoria: "acao",
    label: "Mover pra outra etapa",
    descricao: "Move o lead pra outra etapa do mesmo funil.",
    icone: "MoveRight",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({ funilId: "", etapaTitulo: "" }),
  },
  {
    tipo: "alterar_funil",
    categoria: "acao",
    label: "Mover pra outro funil",
    descricao: "Move o lead pra outro funil.",
    icone: "Shuffle",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({ funilId: "" }),
  },
  {
    tipo: "alterar_responsavel",
    categoria: "acao",
    label: "Atribuir responsável",
    descricao: "Atribui o lead a um atendente da equipe.",
    icone: "UserCheck",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({ atendenteNome: "" }),
  },
  {
    tipo: "encaminhar_equipe",
    categoria: "acao",
    label: "Encaminhar pra equipe",
    descricao: "Encaminha o atendimento pra uma equipe/fila.",
    icone: "Users",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({ equipeNome: "" }),
  },
  {
    tipo: "distribuir_disponibilidade",
    categoria: "acao",
    label: "Distribuir por disponibilidade",
    descricao: "Distribui o lead entre atendentes disponíveis.",
    icone: "Split",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({ modo: "round_robin", equipeNome: "" }),
  },
  {
    tipo: "criar_tarefa",
    categoria: "acao",
    label: "Criar tarefa",
    descricao: "Cria uma tarefa com prazo pro time.",
    icone: "ListPlus",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({
      categoria: "Follow-up",
      titulo: "",
      modoResponsavel: "atual",
      modoPrazo: "depois_de",
      prazoValor: 2,
      prazoUnidade: "horas",
      prioridade: "normal",
      relacionarA: "contato",
    }),
  },
  {
    tipo: "criar_lembrete",
    categoria: "acao",
    label: "Criar lembrete",
    descricao: "Cria um lembrete de follow-up.",
    icone: "BellPlus",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({ titulo: "" }),
  },
  {
    tipo: "atualizar_campo",
    categoria: "acao",
    label: "Atualizar campo do contato",
    descricao: "Grava um valor num campo do contato.",
    icone: "PencilLine",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({ campoNome: "", valor: "" }),
  },
  {
    tipo: "criar_negocio",
    categoria: "acao",
    label: "Criar negócio",
    descricao: "Cria um novo card de negócio pro contato.",
    icone: "BriefcaseBusiness",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({ nome: "", funilId: "", etapaTitulo: "", valor: "" }),
  },
  {
    tipo: "atualizar_valor",
    categoria: "acao",
    label: "Atualizar valor do negócio",
    descricao: "Atualiza o valor do negócio do contato.",
    icone: "DollarSign",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({ modo: "definir", valor: "" }),
  },
  {
    tipo: "atualizar_status",
    categoria: "acao",
    label: "Atualizar status",
    descricao: "Atualiza o status do contato/negócio.",
    icone: "Flag",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({ status: "" }),
  },
  {
    tipo: "agendar_consulta",
    categoria: "acao",
    label: "Agendar consulta",
    descricao: "Agenda uma consulta pro contato.",
    icone: "CalendarPlus",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({ data: "", horario: "", profissional: "", tipoServico: "" }),
  },
  {
    tipo: "cancelar_agendamento",
    categoria: "acao",
    label: "Cancelar agendamento",
    descricao: "Cancela um agendamento existente do contato.",
    icone: "CalendarX",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "enviar_notificacao",
    categoria: "acao",
    label: "Enviar notificação",
    descricao: "Envia uma notificação interna pra equipe.",
    icone: "Bell",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({ mensagem: "" }),
  },
  {
    tipo: "pausar_automacoes",
    categoria: "acao",
    label: "Pausar automações do contato",
    descricao: "Pausa outras automações rodando pro mesmo contato.",
    icone: "Pause",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "cancelar_automacoes",
    categoria: "acao",
    label: "Cancelar automações do contato",
    descricao: "Cancela outras automações rodando pro mesmo contato.",
    icone: "X",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({}),
  },
  {
    tipo: "chamar_webhook",
    categoria: "acao",
    label: "Chamar webhook",
    descricao: "Envia dados pra uma URL externa (simulado — sem backend real).",
    icone: "Webhook",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({ url: "" }),
  },
  {
    tipo: "executar_integracao",
    categoria: "acao",
    label: "Executar integração",
    descricao: "Executa uma ação numa integração conectada (simulado).",
    icone: "Plug",
    corClasse: corDaCategoria("acao"),
    dataPadrao: () => ({}),
  },

  // --------------------------------------------------------------- humano --
  {
    tipo: "encaminhar_humano",
    categoria: "humano",
    label: "Encaminhar pra atendimento humano",
    descricao: "Tira o contato do fluxo automático e passa pra um atendente.",
    icone: "Headset",
    corClasse: corDaCategoria("humano"),
    dataPadrao: () => ({}),
  },

  // ------------------------------------------------------------------ fim --
  {
    tipo: "encerrar_fluxo",
    categoria: "fim",
    label: "Encerrar fluxo",
    descricao: "Termina a execução desse caminho do fluxo.",
    icone: "OctagonX",
    corClasse: corDaCategoria("fim"),
    dataPadrao: () => ({}),
  },
];

/** Checagem em tempo de compilação: todo `FlowNodeType` precisa ter uma entrada aqui. */
type TiposFaltando = Exclude<FlowNodeType, (typeof BLOCOS_DISPONIVEIS)[number]["tipo"]>;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const _blocosCobremTodosOsTipos: TiposFaltando extends never ? true : never = true;

export function buscarBlocos(query: string): BlocoDefinicao[] {
  const termo = query.trim().toLowerCase();
  if (!termo) return BLOCOS_DISPONIVEIS;
  return BLOCOS_DISPONIVEIS.filter(
    (b) =>
      b.label.toLowerCase().includes(termo) ||
      b.descricao.toLowerCase().includes(termo) ||
      b.tipo.toLowerCase().includes(termo),
  );
}
